_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "results/faster_rcnn_R_50_FPN_4x_cb/"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    CHECKERBOARD_RATE: 0.1
    CHECKERBOARD_SIZE: 1
    CHECKERBOARD_SHAPE: "square"
DATALOADER:
  NUM_WORKERS: 10
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (240000, 320000)
  MAX_ITER: 360000
